export enum AppModal {
	REGISTER = "REGISTER",
	ACCOUNT_DELETE_CONFIRM = "DELETE_ACCOUNT_CONFIRM",
	ACCOUNT_MANAGE = "MANAGE_ACCOUNT",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	SESSION_EXPIRE_WARNING = "SESSION_EXPIRE_WARNING",
	SONG_DELETE_CONFIRM = "SONG_DELETE_CONFIRM",
	SONG_SET_DELETE_CONFIRM = "SONG_SET_DELETE_CONFIRM",
}

export enum SectionId {
	SONG = "SONG",
	SONG_SET = "SONG_SET",
	SONG_LIBRARY = "SONG_LIBRARY",
	SONG_SET_LIBRARY = "SONG_SET_LIBRARY",
	TRANSLATION = "TRANSLATION",
	CREDITS = "CREDITS",
	LYICS = "LYICS",
}

export enum ActionResultType {
	ERROR = "ERROR",
	SUCCESS = "SUCCESS",
}
