export enum AppModal {
	REGISTER = "REGISTER",
	DELETE_ACCOUNT_CONFIRM = "DELETE_ACCOUNT_CONFIRM",
	MANAGE_ACCOUNT = "MANAGE_ACCOUNT",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	SESSION_EXPIRE_WARNING = "SESSION_EXPIRE_WARNING",
}

export enum SectionId {
	SONG = "SONG",
	SONG_SET = "SONG_SET",
	SONG_LIBRARY = "SONG_LIBRARY",
	SONG_SET_LIBRARY = "SONG_SET_LIBRARY",
	TRANSLATION = "TRANSLATION",
	CREDITS = "CREDITS",
	LYICS = "LYICS",
}

export enum ActionResultType {
	ERROR = "ERROR",
	SUCCESS = "SUCCESS",
}
