export enum AppModal {
	REGISTER = "REGISTER",
	DELETE_ACCOUNT_CONFIRM = "DELETE_ACCOUNT_CONFIRM",
	MANAGE_ACCOUNT = "MANAGE_ACCOUNT",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	SESSION_EXPIRE_WARNING = "SESSION_EXPIRE_WARNING",
}

export enum SectionId {
	SONG = "SONG",
	SET_LIST = "SET_LIST",
	SONG_LIBRARY = "SONG_LIBRARY",
	TRANSLATION = "TRANSLATION",
}

export enum ActionResultType {
	ERROR = "ERROR",
	SUCCESS = "SUCCESS",
}
