export const sectionId = {
	SONG: "SONG",
	SONG_SET: "SONG_SET",
	SONG_LIBRARY: "SONG_LIBRARY",
	SONG_SET_LIBRARY: "SONG_SET_LIBRARY",
	TRANSLATION: "TRANSLATION",
	CREDITS: "CREDITS",
	LYICS: "LYICS",
} as const;
