export const sectionId = {
	SONG: "SONG",
	PLAYLIST: "SONG_SET",
	SONG_LIBRARY: "SONG_LIBRARY",
	PLAYLIST_LIBRARY: "SONG_SET_LIBRARY",
	TRANSLATION: "TRANSLATION",
	CREDITS: "CREDITS",
	LYICS: "LYICS",
	LOG: "LOG",
	QR: "QR",
} as const;
