export const enum Section {
	SONG = "so",
	SONG_LIBRARY = "sl",
	TRANSLATION = "tr",
	CREDITS = "cr",
	LYRICS = "l",
	KEY = "k",
	SCALE = "sc",
	SCALE_DEGREES = "sd",
	CHORD = "c",
	CHORD_SCALE_DEGREE = "csd",
	POSITIONS = "ps",
	INSTRUMENT = "i",
	TUNING = "t",
	FRETBOARD = "f",
	STATE = "st",
	QRCODE = "q",
}
